import { ShieldCheck, Mail, Phone, MapPin, Scale, AlertTriangle } from "lucide-react";

const SECTIONS: { title: string; body: React.ReactNode }[] = [
  {
    title: "1. About Lasa Research & This Agreement",
    body: (
      <>
        <p>
          Lasa Research ("Lasa Research", "we", "us", "our") is a proprietorship of Dheeraj Sogani,
          registered with the Securities and Exchange Board of India (SEBI) as a Research Analyst
          under Registration No. <strong>INH000030144</strong>.
        </p>
        <p>
          These Terms and Conditions ("Terms") govern your access to and use of the Lasa Research
          website, dashboard, and any research reports, screeners, trade ideas, or communications we
          provide (collectively, the "Services"). By creating an account, subscribing to a paid plan,
          or otherwise using the Services, you agree to be bound by these Terms.
        </p>
      </>
    ),
  },
  {
    title: "2. Eligibility",
    body: (
      <p>
        The Services are intended for individuals who are at least 18 years of age and legally
        competent to enter into a binding contract under the Indian Contract Act, 1872. By using the
        Services, you represent that you meet this requirement and that the KYC details you provide
        to us are true, complete, and current.
      </p>
    ),
  },
  {
    title: "3. Scope of Services",
    body: (
      <>
        <p>
          Lasa Research is a research-only service provider. Our role is strictly limited to
          publishing independent research, analytical scans, and educational market commentary. We do
          not:
        </p>
        <ul className="list-disc pl-5 space-y-1.5">
          <li>Execute trades, manage funds, or act as a portfolio manager on your behalf</li>
          <li>Guarantee, promise, or assure any specific return, profit, or outcome</li>
          <li>Provide personalized investment advice tailored to your individual financial situation</li>
        </ul>
        <p>
          All scores, screeners, signals, and trade ideas on the platform are generated end-to-end by
          proprietary algorithmic and AI-based methodologies, reviewed and approved by Dheeraj Sogani,
          who remains the Research Analyst responsible for this research.
        </p>
      </>
    ),
  },
  {
    title: "4. Subscription Plans & Fees",
    body: (
      <>
        <p>
          Lasa Research offers a free tier and paid subscription tiers (currently marketed as
          Starter, Analyst, and Pro Trader), each with its own fee and feature set as displayed on our{" "}
          <a href="/pricing" className="text-primary underline underline-offset-2">Pricing</a> page at
          the time of purchase. Fees are charged in Indian Rupees (₹) on a recurring monthly or annual
          basis, as selected by you, and are subject to the fee limits prescribed under the SEBI
          (Research Analysts) Regulations, 2014 and applicable SEBI circulars issued from time to
          time.
        </p>
        <p>
          We reserve the right to revise subscription fees prospectively. Any change will not affect
          an already-active billing cycle; the new fee applies from your next renewal.
        </p>
      </>
    ),
  },
  {
    title: "5. Payment Methods",
    body: (
      <p>
        Payments are accepted via UPI, debit/credit card, net banking, and bank transfer through our
        payment gateway partner. <strong>Cash payments are not accepted</strong> under any
        circumstances, in line with SEBI's guidelines for research analyst fee collection.
      </p>
    ),
  },
  {
    title: "6. Risk Disclosure",
    body: (
      <>
        <p className="font-semibold text-foreground/90">
          Investments in securities markets are subject to market risks. There is no assurance or
          guarantee of returns.
        </p>
        <ul className="list-disc pl-5 space-y-1.5">
          <li>
            All content on the platform — scans, screeners, technical levels, and trade ideas — is
            generated by algorithmic and AI models for educational and informational purposes only,
            and does not constitute a recommendation to buy, sell, or hold any security.
          </li>
          <li>Past performance of any scan, strategy, or recommendation is not indicative of future results.</li>
          <li>
            You should independently evaluate all information and, where appropriate, consult a
            qualified, SEBI-registered financial advisor before making any investment decision.
          </li>
          <li>Lasa Research and its Research Analyst are not liable for any financial loss arising from reliance on the Services.</li>
        </ul>
      </>
    ),
  },
  {
    title: "7. Know Your Customer (KYC)",
    body: (
      <p>
        You are required to provide accurate and complete KYC information (name, contact details, and
        any other information we reasonably request) before we can activate or continue your paid
        subscription. We may suspend access to the Services if KYC details are found to be incomplete,
        inaccurate, or unverifiable.
      </p>
    ),
  },
  {
    title: "8. Refunds & Cancellation",
    body: (
      <>
        <p>
          You may cancel a paid subscription at any time from your account settings. Upon
          cancellation, you will retain access to paid features for the remainder of the period
          already paid for; no further renewal will be charged.
        </p>
        <p>
          Where a subscription is cancelled prematurely for reasons attributable to Lasa Research
          (e.g. discontinuation of the Service), a pro-rata refund for the unused portion of the
          subscription period will be processed to your original payment method.
        </p>
      </>
    ),
  },
  {
    title: "9. User Conduct & Prohibited Use",
    body: (
      <p>
        You agree not to reproduce, redistribute, resell, or make commercially available any research
        content from the Services without our prior written consent; not to use the Services for any
        unlawful purpose; and not to attempt to circumvent subscription tiers or access controls.
      </p>
    ),
  },
  {
    title: "10. Intellectual Property",
    body: (
      <p>
        All content, methodology documentation, screeners, branding, and software underlying the
        Services are the property of Lasa Research (or its licensors) and are protected under
        applicable intellectual property laws. Your subscription grants a limited, non-transferable,
        revocable licence to use the Services for personal, non-commercial purposes only.
      </p>
    ),
  },
  {
    title: "11. Data Protection",
    body: (
      <p>
        We take reasonable technical and organisational measures to protect the personal and KYC
        information you share with us. However, no method of electronic transmission or storage is
        completely secure, and we cannot guarantee absolute security of data transmitted over the
        internet.
      </p>
    ),
  },
  {
    title: "12. Limitation of Liability",
    body: (
      <p>
        To the maximum extent permitted by law, Lasa Research's total liability arising out of or
        relating to the Services shall not exceed the subscription fees paid by you in the twelve (12)
        months preceding the event giving rise to the claim. Lasa Research shall not be liable for any
        indirect, incidental, or consequential loss, including trading losses.
      </p>
    ),
  },
  {
    title: "13. Grievance Redressal",
    body: (
      <>
        <p>
          If you have a complaint or grievance regarding the Services, please write to our Compliance
          Officer at{" "}
          <a href="mailto:dheeraj_sogani@yahoo.com" className="text-primary underline underline-offset-2">
            dheeraj_sogani@yahoo.com
          </a>{" "}
          . We aim to acknowledge and resolve grievances within 7 business days.
        </p>
        <p>
          If you are not satisfied with our resolution, you may escalate your complaint through
          SEBI's SCORES portal (
          <a
            href="https://scores.sebi.gov.in"
            target="_blank"
            rel="noopener noreferrer"
            className="text-primary underline underline-offset-2"
          >
            scores.sebi.gov.in
          </a>
          ) or the Smart ODR portal for online dispute resolution.
        </p>
      </>
    ),
  },
  {
    title: "14. Governing Law & Jurisdiction",
    body: (
      <p>
        These Terms are governed by the laws of India. Subject to SEBI's dispute resolution
        mechanisms described above, any dispute arising out of or in connection with these Terms shall
        be subject to the exclusive jurisdiction of the courts at Noida, Uttar Pradesh.
      </p>
    ),
  },
  {
    title: "15. Amendments",
    body: (
      <p>
        We may revise these Terms from time to time to reflect changes in our Services or applicable
        regulation. The updated Terms will be posted on this page with a revised effective date.
        Continued use of the Services after such changes constitutes acceptance of the revised Terms.
      </p>
    ),
  },
];

export function Terms() {
  const effectiveDate = new Date().toLocaleDateString("en-IN", {
    day: "numeric",
    month: "long",
    year: "numeric",
  });

  return (
    <div className="min-h-screen bg-[#020617] text-foreground selection:bg-primary/30 font-sans pb-20">
      <div className="relative container mx-auto px-4 py-10 max-w-3xl">
        {/* Header */}
        <div className="mb-8 space-y-3">
          <div className="inline-flex items-center gap-2 px-3 py-1 rounded-full bg-primary/10 border border-primary/20 text-primary text-xs font-black uppercase tracking-widest">
            <Scale className="w-3.5 h-3.5" />
            Legal
          </div>
          <h1 className="text-3xl md:text-4xl font-black tracking-tight text-white">Terms &amp; Conditions</h1>
          <p className="text-xs text-muted-foreground font-medium">Effective {effectiveDate}</p>
        </div>

        {/* Registration summary card */}
        <div className="mb-10 p-5 rounded-2xl bg-white/[0.02] border border-white/10 space-y-2.5 text-sm">
          <div className="flex items-start gap-2.5">
            <ShieldCheck className="w-4 h-4 text-primary mt-0.5 shrink-0" />
            <span>
              <strong className="text-foreground/90">Lasa Research</strong> — SEBI Registered Research
              Analyst, Regn. No. <strong>INH000030144</strong>. Proprietor: Dheeraj Sogani.
            </span>
          </div>
          <div className="flex items-start gap-2.5">
            <MapPin className="w-4 h-4 text-primary mt-0.5 shrink-0" />
            <span className="text-muted-foreground">
              Registered Office: L1604, Ajnara Grand Heritage, Sector 74, Noida, Uttar Pradesh
            </span>
          </div>
          <div className="flex items-start gap-2.5">
            <Mail className="w-4 h-4 text-primary mt-0.5 shrink-0" />
            <a href="mailto:dheeraj_sogani@yahoo.com" className="text-muted-foreground hover:text-primary transition-colors">
              dheeraj_sogani@yahoo.com
            </a>
          </div>
          <div className="flex items-start gap-2.5">
            <Phone className="w-4 h-4 text-primary mt-0.5 shrink-0" />
            <span className="text-muted-foreground">
              Compliance Officer: Dheeraj Sogani · +91 95551 51691
            </span>
          </div>
        </div>

        {/* Sections */}
        <div className="space-y-8">
          {SECTIONS.map((section) => (
            <section key={section.title} className="space-y-2.5">
              <h2 className="text-base font-bold text-white tracking-tight">{section.title}</h2>
              <div className="text-sm text-muted-foreground leading-relaxed space-y-2.5">{section.body}</div>
            </section>
          ))}
        </div>

        {/* Footer disclaimer strip */}
        <div className="mt-12 p-4 rounded-xl bg-amber-500/5 border border-amber-500/20 flex items-start gap-2.5 text-[11px] text-muted-foreground leading-relaxed">
          <AlertTriangle className="w-4 h-4 text-amber-500 mt-0.5 shrink-0" />
          <span>
            Registration granted by SEBI and certification from NISM in no way guarantee the
            performance of the intermediary or provide any assurance of returns to investors.
          </span>
        </div>
      </div>
    </div>
  );
}

export default Terms;
